name = "ck-machine-invariant"
version = "0.1.0"
defaultTargets = ["ck-machine-invariant"]

[[lean_lib]]
name = "ArithmeticCKMachine"

[[lean_exe]]
name = "ck-machine-invariant"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
