[project]
name = "arithmetic-reduction-animation-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
    "mypy>=1.16.0",
    "ruff>=0.11.13",
]
